from enum import Enum


class GenerationAuditAction(str, Enum):
    GENERATION_INITIATED = "GENERATION_INITIATED"
    SECTION_GENERATION_COMPLETED = "SECTION_GENERATION_COMPLETED"
    SECTION_GENERATION_FAILED = "SECTION_GENERATION_FAILED"
    BATCH_GENERATION_COMPLETED = "BATCH_GENERATION_COMPLETED"
    BATCH_GENERATION_FAILED = "BATCH_GENERATION_FAILED"
    DOCUMENT_ASSEMBLY_COMPLETED = "DOCUMENT_ASSEMBLY_COMPLETED"
    DOCUMENT_ASSEMBLY_FAILED = "DOCUMENT_ASSEMBLY_FAILED"
    DOCUMENT_RENDERING_COMPLETED = "DOCUMENT_RENDERING_COMPLETED"
    DOCUMENT_RENDERING_FAILED = "DOCUMENT_RENDERING_FAILED"
    DOCUMENT_VERSION_CREATED = "DOCUMENT_VERSION_CREATED"
    # Regeneration actions
    REGENERATION_INITIATED = "REGENERATION_INITIATED"
    REGENERATION_COMPLETED = "REGENERATION_COMPLETED"
    REGENERATION_FAILED = "REGENERATION_FAILED"
    SECTION_REGENERATED = "SECTION_REGENERATED"
    SECTION_REUSED = "SECTION_REUSED"
    TEMPLATE_VERSION_TRANSITION = "TEMPLATE_VERSION_TRANSITION"


class GenerationAuditEntityType(str, Enum):
    GENERATION_BATCH = "GENERATION_BATCH"
    SECTION_OUTPUT = "SECTION_OUTPUT"
    SECTION_OUTPUT_BATCH = "SECTION_OUTPUT_BATCH"
    ASSEMBLED_DOCUMENT = "ASSEMBLED_DOCUMENT"
    RENDERED_DOCUMENT = "RENDERED_DOCUMENT"
    DOCUMENT_VERSION = "DOCUMENT_VERSION"
    # Regeneration entities
    REGENERATION_BATCH = "REGENERATION_BATCH"
    DOCUMENT = "DOCUMENT"
